### ISSUE TITLE
EXE双击无显示，运行GUI提示找不到文件

### ISSUE THREAD

**Issue by pingal-alealeale** [hiroi-sora/Umi-OCR#221]
<img width="734" alt="error" src="https://github.com/hiroi-sora/Umi-OCR/assets/149837081/781a0120-1a84-4d15-8061-4061ec6fb8e0">

**Comment by hiroi-sora** [comment]
看起来工作路径不对劲，启动脚本的工作路径是`C:\Windows\System32`而不是Umi-OCR目录下，所以相对路径找不到文件。

你是双击启动bat的还是在命令行里启动的？

另外，试下在命令行里启动exe，看看有何输出？（即在Umi-OCR目录下，shift+右键→在此处打开Powershell→输入`./Umi-OCR.exe`→回车）

**Comment by pingal-alealeale** [comment]
在下载文件夹解压缩后在powershell运行是这样：
PS C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025> .\Umi-OCR.exe
PS C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025> Traceback (most recent call last):
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 58, in load
    dependencies, libzbar = load_objects(Path(''))
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 50, in load_objects
    deps = [
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 51, in <listcomp>
    cdll.LoadLibrary(str(directory.joinpath(dep)))
  File "ctypes\__init__.py", line 451, in LoadLibrary
  File "ctypes\__init__.py", line 373, in __init__
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\main.py", line 60, in <module>
    runScript()  # 启动脚本
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\main.py", line 55, in runScript
    main()
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\py_src\run.py", line 109, in main
    res = runQml()  # 启动qml
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\py_src\run.py", line 25, in runQml
    from .tag_pages.tag_pages_connector import TagPageConnector  # 页面连接器
  File "C:\Users\S\AppData\Local\Temp\embedded.6usagh_w.zip\shibokensupport\__feature__.py", line 142, in _import
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\py_src\tag_pages\tag_pages_connector.py", line 15, in <module>
    from .QRcode import QRcode
  File "C:\Users\S\AppData\Local\Temp\embedded.6usagh_w.zip\shibokensupport\__feature__.py", line 142, in _import
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\py_src\tag_pages\QRcode.py", line 12, in <module>
    import pyzbar.pyzbar as pyzbar
  File "C:\Users\S\AppData\Local\Temp\embedded.6usagh_w.zip\shibokensupport\__feature__.py", line 142, in _import
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "C:\Users\S\AppData\Local\Temp\embedded.6usagh_w.zip\shibokensupport\__feature__.py", line 142, in _import
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 60, in load
    dependencies, libzbar = load_objects(Path(__file__).parent)
  File "C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 54, in load_objects
    libzbar = cdll.LoadLibrary(str(directory.joinpath(fname)))
  File "ctypes\__init__.py", line 451, in LoadLibrary
  File "ctypes\__init__.py", line 373, in __init__
FileNotFoundError: Could not find module 'C:\Users\S\Downloads\Umi-OCR_Paddle_dev_20231025\UmiOCR-data\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

将Umi-OCR.exe和UmiOCR-data拷贝到system32文件夹下，运行powershell是这样：
PS C:\Windows\System32\UmiOCR-data> .\RUN_GUI.bat

C:\Windows\System32\UmiOCR-data>start "" runtime/pythonw.exe main.py
PS C:\Windows\System32\UmiOCR-data>

________________________________
发件人: hiroi-sora ***@***.***>
发送时间: 2023年11月4日 15:18
收件人: hiroi-sora/Umi-OCR ***@***.***>
抄送: pingal-alealeale ***@***.***>; Author ***@***.***>
主题: Re: [hiroi-sora/Umi-OCR] EXE双击无显示，运行GUI提示找不到文件 (Issue #221)


看起来工作路径不对劲，启动脚本的工作路径是C:\Windows\System32而不是Umi-OCR目录下，所以相对路径找不到文件。

你是双击启动bat的还是在命令行里启动的？

另外，试下在命令行里启动exe，看看有何输出？（即在Umi-OCR目录下，shift+右键→在此处打开Powershell→输入./Umi-OCR.exe→回车）

―

**Comment by hiroi-sora** [comment]
哦哦，此bug已在新的预览版里修复。麻烦下载个新版试试。
