### ISSUE TITLE
win7  双击Umi-OCR2.0均无反应 进程里也没

### ISSUE THREAD

**Issue by jzysl423** [hiroi-sora/Umi-OCR#250]
`
D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data>D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\main.py
Traceback (most recent call last):
  File "D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\main.py", line 65, in <module>
    runScript()  # 启动脚本
  File "D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\main.py", line 58, in runScript
    from py_src.run import main
  File "D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\py_src\run.py", line 6, in <module>
    from .server.cmd_client import initCmd
  File "D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\py_src\server\cmd_client.py", line 11, in <module>
    import psutil
  File "D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ImportError: DLL load failed while importing _psutil_windows: %1 不是有效的 Win32 应用程序。

D:\ocr\Umi-OCR_Paddle_v2.0.0\UmiOCR-data>`

运行main.py的错误

**Comment by hiroi-sora** [comment]
直接用本地python环境运行main.py确实是不能跑起来哒。

请尝试一下：运行 `UmiOCR-data/RUN_CLI.bat` ，看看控制台有什么输出或报错？

**Comment by jzysl423** [comment]
```

D:\ocr\Umi-OCR_Rapid_v2.0.0\UmiOCR-data>start "" runtime/python.exe main.py

D:\ocr\Umi-OCR_Rapid_v2.0.0\UmiOCR-data>pause
请按任意键继续. . .
```
运行后闪了一下就没了

**Comment by hiroi-sora** [comment]
好的，那么麻烦在命令行中运行 Umi-OCR.exe 试试？

**Comment by hiroi-sora** [comment]
我暂时无法判断这是什么情况，抱歉。

如果有需求，请先使用 v1.3.7 版：
https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.7

**Comment by wangjiahao123456** [comment]
v1.3.7可以正常运行，可是v1.3.7不支持http请求
